import test from 'node:test';
import assert from 'node:assert/strict';
import {handleExtras,handlePublicFeedback} from '../backend/src/extras.js';
const origin='https://family.pages.dev';
function fake(){const calls=[];return {calls,DB:{prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return {n:0}},async all(){return {results:[]}},async run(){calls.push({sql,args});return {meta:{changes:1}}}}},async batch(statements){calls.push({batch:statements.length})}}}}
function req(path,body,method='POST'){return new Request(origin+path,{method,headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)})}
test('jar allocation rejects sums other than 100 and saves valid changes atomically',async()=>{const env=fake();const bad=await handleExtras(req('/api/jars',{jars:[{name:'Needs',percent:90,color:'#123456'}]},'PUT'),env,'/api/jars','mom@example.com');assert.equal(bad.status,400);assert.equal(env.calls.length,0);const good=await handleExtras(req('/api/jars',{jars:[{name:'Needs',percent:60,color:'#123456'},{name:'Travel',percent:40,color:'#abcdef'}]},'PUT'),env,'/api/jars','mom@example.com');assert.equal(good.status,200);assert.equal(env.calls[0].batch,3)});
test('offer requires a real price and HTTPS source',async()=>{const env=fake();const bad=await handleExtras(req('/api/offers',{product:'Pork',store:'Netto',price:0,url:'http://example.com'}),env,'/api/offers','mom@example.com');assert.equal(bad.status,400);const good=await handleExtras(req('/api/offers',{product:'Pork 500g',store:'Netto',price:25,url:'https://netto.dk/'}),env,'/api/offers','mom@example.com');assert.equal(good.status,201);assert.equal(env.calls.length,1);assert.equal(env.calls[0].args.length,11)});
test('public feedback requires same origin and stores message without exposing it',async()=>{const env=fake();const wrong=await handlePublicFeedback(new Request(origin+'/api/feedback',{method:'POST',headers:{origin:'https://attacker.example','content-type':'application/json'},body:JSON.stringify({message:'Useful idea for family'})}),env);assert.equal(wrong.status,403);const saved=await handlePublicFeedback(req('/api/feedback',{message:'Please add weekly planning',contact:'visitor@example.com'}),env);assert.equal(saved.status,201);assert.equal(env.calls[0].args[1],'visitor@example.com')});
