import {handleExtras, handlePublicFeedback} from './extras.js';
const KINDS = new Set(['income','expense','claim','tax','saving','event','health','food','meal','meal_log','wardrobe','idea','household','shopping','task','wishlist','diary']);
const DAY = 86400;
const json = (data,status=200,headers={}) => new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const error = (message,status=400)=>json({error:message},status);
const base64 = bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unbase64 = str=>Uint8Array.from(atob(str.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
const hash = async str=>base64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(str)));
const random = ()=>base64(crypto.getRandomValues(new Uint8Array(32)));
const cookie = (name,value,maxAge)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const parseCookie = (req,name)=>req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1);
const safe = (v,n=1000)=>String(v??'').slice(0,n);
const authUrl='/api/auth/start';
const redirectUri = (req)=>new URL('/api/auth/callback',req.url).toString();
function credentials(env){return env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET && env.TOKEN_ENCRYPTION_KEY && env.DB && env.BUCKET && env.ALLOWED_EMAILS;}
async function encrypt(value,env){const key=await crypto.subtle.importKey('raw',unbase64(env.TOKEN_ENCRYPTION_KEY),{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value));return base64(iv)+'.'+base64(ciphertext)}
async function decrypt(value,env){const [iv,data]=value.split('.');const key=await crypto.subtle.importKey('raw',unbase64(env.TOKEN_ENCRYPTION_KEY),{name:'AES-GCM'},false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unbase64(iv)},key,unbase64(data)))}
async function currentUser(req,env){const token=parseCookie(req,'family_session');if(!token)return null;const row=await env.DB.prepare('SELECT email FROM sessions WHERE token_hash=? AND expires_at>?').bind(await hash(token),Math.floor(Date.now()/1000)).first();if(!row)return null;const allowed=env.ALLOWED_EMAILS.split(',').map(x=>x.trim().toLowerCase());return allowed.includes(row.email.toLowerCase())?row.email:null}
function authStart(req,env){const state=random();const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');for(const [k,v] of Object.entries({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:redirectUri(req),response_type:'code',scope:'openid email https://www.googleapis.com/auth/calendar.events',access_type:'offline',prompt:'consent',state}))url.searchParams.set(k,v);return new Response(null,{status:302,headers:{Location:url.toString(),'Set-Cookie':cookie('family_oauth_state',state,600),'Cache-Control':'no-store'}})}
async function authCallback(req,env){const url=new URL(req.url),state=url.searchParams.get('state'),saved=parseCookie(req,'family_oauth_state');if(!state||!saved||state!==saved)return error('Kết nối Google không hợp lệ. Hãy thử lại.',403);if(url.searchParams.has('error'))return error('Bạn chưa cho phép truy cập Google Calendar.',403);const code=url.searchParams.get('code');if(!code)return error('Thiếu mã xác thực.',400);
 const tokenResponse=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:redirectUri(req),grant_type:'authorization_code'})});const tokens=await tokenResponse.json();if(!tokenResponse.ok||!tokens.access_token)return error('Google chưa cấp quyền. Vui lòng thử kết nối lại.',502);
 const profileResponse=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+tokens.access_token}});const profile=await profileResponse.json();if(!profileResponse.ok||!profile.email||profile.email_verified!==true)return error('Không xác minh được email Google.',403);
 const email=profile.email.toLowerCase();if(!env.ALLOWED_EMAILS.split(',').map(x=>x.trim().toLowerCase()).includes(email))return error('Email này chưa được thêm vào danh sách thành viên gia đình.',403);
 if(tokens.refresh_token){const encrypted=await encrypt(tokens.refresh_token,env);await env.DB.prepare('INSERT INTO google_connections(email,refresh_token_encrypted,updated_at) VALUES(?,?,?) ON CONFLICT(email) DO UPDATE SET refresh_token_encrypted=excluded.refresh_token_encrypted,updated_at=excluded.updated_at').bind(email,encrypted,Date.now()).run()}
 const session=random();await env.DB.prepare('INSERT INTO sessions(token_hash,email,expires_at) VALUES(?,?,?)').bind(await hash(session),email,Math.floor(Date.now()/1000)+DAY*30).run();const headers=new Headers({Location:'/', 'Cache-Control':'no-store'});headers.append('Set-Cookie',cookie('family_oauth_state','',0));headers.append('Set-Cookie',cookie('family_session',session,DAY*30));return new Response(null,{status:302,headers})}
async function accessToken(email,env){const connection=await env.DB.prepare('SELECT refresh_token_encrypted FROM google_connections WHERE email=?').bind(email).first();if(!connection)return null;const token=await decrypt(connection.refresh_token_encrypted,env);const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,refresh_token:token,grant_type:'refresh_token'})});const data=await response.json();if(!response.ok)throw new Error('Google Calendar cần kết nối lại.');return data.access_token}
async function calendarList(req,email,env){const access=await accessToken(email,env);if(!access)return error('Chưa kết nối Google Calendar.',409);const params=new URL(req.url).searchParams,from=params.get('from'),to=params.get('to');if((from||to)&&(!from||!to||!Number.isFinite(Date.parse(from))||!Number.isFinite(Date.parse(to))||Date.parse(to)<=Date.parse(from)||Date.parse(to)-Date.parse(from)>370*86400000))return error('Khoảng ngày lịch không hợp lệ.');const calendarId=encodeURIComponent(env.FAMILY_CALENDAR_ID||'primary');const url=new URL(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events`);url.searchParams.set('timeMin',from||new Date().toISOString());if(to)url.searchParams.set('timeMax',to);url.searchParams.set('maxResults',from?'250':'30');url.searchParams.set('singleEvents','true');url.searchParams.set('orderBy','startTime');const response=await fetch(url,{headers:{Authorization:'Bearer '+access}});const data=await response.json();if(!response.ok)return error('Không lấy được lịch Google. Kiểm tra quyền truy cập lịch chung.',502);return json((data.items||[]).map(x=>({id:x.id,title:x.summary||'Không có tên',start:x.start?.dateTime||x.start?.date,end:x.end?.dateTime||x.end?.date,link:x.htmlLink}))) }
async function sendCalendar(req,email,env){const body=await req.json();const id=safe(body.id,100);const row=await env.DB.prepare("SELECT id,title,date,time,person,note,details FROM records WHERE id=? AND household_id='family' AND kind='event'").bind(id).first();if(!row)return error('Không tìm thấy lịch.',404);if(!/^\d{4}-\d{2}-\d{2}$/.test(row.date||''))return error('Lịch cần có ngày hợp lệ.');let eventDetails={};try{eventDetails=JSON.parse(row.details||'{}')||{}}catch{}if(eventDetails.googleEventId)return error('Lịch này đã được gửi sang Google Calendar.',409)
 const access=await accessToken(email,env);if(!access)return error('Hãy kết nối Google Calendar.',409);const start=`${row.date}T${/^\d\d:\d\d$/.test(row.time||'')?row.time:'09:00'}:00`;const payload={summary:`${row.title} · ${row.person}`,description:row.note||'',start:{dateTime:start,timeZone:'Europe/Copenhagen'},end:{dateTime:start,timeZone:'Europe/Copenhagen'}};
 // Build local end time from the chosen start; Calendar interprets the explicit zone correctly through DST.
 const [hour,min]=start.slice(11,16).split(':').map(Number);const endMinutes=hour*60+min+60;payload.end={dateTime:`${row.date}T${String(Math.floor(endMinutes/60)%24).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}:00`,timeZone:'Europe/Copenhagen'};
 if(endMinutes>=1440){const next=new Date(row.date+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+1);payload.end.dateTime=next.toISOString().slice(0,10)+payload.end.dateTime.slice(10)}
 if(['daily','weekly','monthly','yearly'].includes(eventDetails.recurrence?.frequency)){const r=eventDetails.recurrence;const freq={daily:'DAILY',weekly:'WEEKLY',monthly:'MONTHLY',yearly:'YEARLY'}[r.frequency];payload.recurrence=['RRULE:FREQ='+freq+(r.until&&/^\d{4}-\d{2}-\d{2}$/.test(r.until)?';UNTIL='+r.until.replace(/-/g,'')+'T235959Z':'')]}
 const calendarId=encodeURIComponent(env.FAMILY_CALENDAR_ID||'primary');const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events`,{method:'POST',headers:{Authorization:'Bearer '+access,'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)return error('Không gửi được lịch lên Google Calendar. Kiểm tra quyền chỉnh sửa lịch chung.',502);await env.DB.prepare('UPDATE records SET details=? WHERE id=?').bind(JSON.stringify({...eventDetails,googleEventId:data.id,googleLink:data.htmlLink}),id).run();return json({id:data.id,link:data.htmlLink})}
async function records(req,env,path){if(req.method==='GET')return json((await env.DB.prepare("SELECT * FROM records WHERE household_id='family' ORDER BY COALESCE(date,'') DESC, created_at DESC LIMIT 3000").all()).results);if(req.method==='POST'){const body=await req.json();if(!KINDS.has(body.kind)||!safe(body.title,180).trim())return error('Loại mục và tên không hợp lệ.');const amount=body.amount===''||body.amount==null?null:Number(body.amount),quantity=body.quantity===''||body.quantity==null?null:Number(body.quantity);if((amount!==null&&!Number.isFinite(amount))||(quantity!==null&&!Number.isFinite(quantity)))return error('Số không hợp lệ.');const record={id:crypto.randomUUID(),household_id:'family',kind:body.kind,title:safe(body.title,180),person:safe(body.person,60)||'Cả nhà',category:safe(body.category,80),amount,quantity,unit:safe(body.unit,30),date:safe(body.date,30),time:safe(body.time,5),status:'open',note:safe(body.note,body.kind==='diary'?12000:2000),image_key:safe(body.image_key,150),details:safe(body.details,body.kind==='meal'||body.kind==='idea'?12000:2000),created_at:Date.now()};await env.DB.prepare('INSERT INTO records(id,household_id,kind,title,person,category,amount,quantity,unit,date,time,status,note,image_key,details,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(...Object.values(record)).run();return json(record,201)}
 if(req.method==='PATCH'){const body=await req.json();const id=safe(body.id,100);const fields=['title','person','category','amount','quantity','unit','date','time','status','note','details','image_key'].filter(k=>Object.prototype.hasOwnProperty.call(body,k));if(!id||!fields.length)return error('Thiếu thông tin thay đổi.');const values=fields.map(k=>['amount','quantity'].includes(k)?(body[k]===''||body[k]==null?null:Number(body[k])):safe(body[k],k==='note'||k==='details'?12000:180));if(values.some(v=>typeof v==='number'&&!Number.isFinite(v)))return error('Số không hợp lệ.');const result=await env.DB.prepare(`UPDATE records SET ${fields.map(k=>k+'=?').join(',')} WHERE id=? AND household_id='family'`).bind(...values,id).run();return result.meta.changes?json({ok:true}):error('Không tìm thấy mục.',404)}
 if(req.method==='DELETE'){const id=new URL(req.url).searchParams.get('id');if(!id)return error('Thiếu mã mục.');await env.DB.prepare("DELETE FROM records WHERE id=? AND household_id='family'").bind(id).run();return json({ok:true})}return error('Phương thức không hỗ trợ.',405)}
async function photos(req,env,path){if(req.method==='POST'&&path==='/api/photos'){const data=await req.formData(),file=data.get('file');if(!(file instanceof File)||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8_000_000)return error('Chọn ảnh JPEG/PNG/WebP dưới 8 MB.');const key=crypto.randomUUID();await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type}});return json({key})}if(req.method==='GET'){const key=path.slice('/api/photos/'.length);if(!/^[a-f0-9-]{36}$/.test(key))return error('Ảnh không hợp lệ.',404);const object=await env.BUCKET.get(key);return object?new Response(object.body,{headers:{'content-type':object.httpMetadata?.contentType||'image/jpeg','cache-control':'private, max-age=300'}}):error('Không tìm thấy ảnh.',404)}return error('Phương thức không hỗ trợ.',405)}
export async function handle({request,env}){const path=new URL(request.url).pathname;try{if(!credentials(env))return error('Chưa cấu hình Google OAuth, database hoặc kho ảnh.',503);if(path==='/api/auth/start')return authStart(request,env);if(path==='/api/auth/callback')return authCallback(request,env);if(path==='/api/feedback'&&request.method==='POST')return handlePublicFeedback(request,env);const email=await currentUser(request,env);if(!email)return error('Vui lòng đăng nhập bằng tài khoản gia đình.',401);if(path==='/api/auth/me')return json({email});if(path==='/api/auth/logout'){const token=parseCookie(request,'family_session');if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(token)).run();return json({ok:true},200,{'set-cookie':cookie('family_session','',0)})}
 if(!['GET','HEAD'].includes(request.method)&&request.headers.get('origin')!==new URL(request.url).origin)return error('Yêu cầu không hợp lệ.',403);
 if(path==='/api/records')return records(request,env,path);if(path==='/api/photos'||path.startsWith('/api/photos/'))return photos(request,env,path);if(path==='/api/calendar/events'&&request.method==='GET')return calendarList(request,email,env);if(path==='/api/calendar/send'&&request.method==='POST')return sendCalendar(request,email,env);const extra=await handleExtras(request,env,path,email);if(extra)return extra;return error('Không tìm thấy API.',404)}catch(err){console.error('API failure',err);return error('Không thể xử lý yêu cầu. Hãy thử lại hoặc kết nối Google lại.',503)}}
