const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const error=(message,status=400)=>json({error:message},status);
const safe=(value,max)=>String(value??'').trim().slice(0,max);
const parse=async request=>{try{return await request.json()}catch{return {}}};
const defaultJars=[['Thiết yếu',55,'#436c60'],['Tự do tài chính',10,'#c59562'],['Giáo dục',10,'#6e8b9b'],['Dự phòng',10,'#a97969'],['Tận hưởng',10,'#bba363'],['Cho đi',5,'#8882a1']].map(([name,percent,color],i)=>({id:`default-${i}`,name,percent,color,sort_order:i}));
export async function handleExtras(request,env,path,email){const method=request.method;
 if(path==='/api/feedback'&&method==='GET')return json((await env.DB.prepare('SELECT id,contact,message,created_at FROM feedback ORDER BY created_at DESC LIMIT 100').all()).results);
 if(path==='/api/jars'){
  if(method==='GET'){const rows=(await env.DB.prepare("SELECT id,name,percent,color,sort_order FROM jar_settings WHERE household_id='family' ORDER BY sort_order").all()).results;return json(rows.length?rows:defaultJars)}
  if(method==='PUT'){const data=await parse(request),rows=data.jars;if(!Array.isArray(rows)||rows.length<1||rows.length>12)return error('Chọn từ 1 đến 12 hũ.');let sum=0;const clean=[];for(const [i,row] of rows.entries()){const percent=Number(row.percent),name=safe(row.name,50),color=safe(row.color,40);if(!name||!Number.isFinite(percent)||percent<0||percent>100||!(/^(#[0-9a-fA-F]{6}|icon:[a-z]{3,20})$/.test(color)))return error('Tên, màu hoặc tỷ lệ hũ không hợp lệ.');sum+=percent;clean.push({id:/^(default-\d+|[a-f0-9-]{36})$/.test(String(row.id||''))?row.id:crypto.randomUUID(),name,percent,color,sort_order:i})}if(new Set(clean.map(x=>x.id)).size!==clean.length)return error('Mã hũ bị trùng.');if(Math.abs(sum-100)>0.001)return error('Tổng tỷ lệ các hũ phải bằng 100%.');await env.DB.batch([env.DB.prepare("DELETE FROM jar_settings WHERE household_id='family'"),...clean.map(x=>env.DB.prepare('INSERT INTO jar_settings(id,household_id,name,percent,color,sort_order) VALUES(?,\'family\',?,?,?,?)').bind(x.id,x.name,x.percent,x.color,x.sort_order))]);return json(clean)}return error('Phương thức không hỗ trợ.',405)}
 if(path==='/api/members'){
  if(method==='GET')return json((await env.DB.prepare("SELECT id,name,avatar_key,favorite_colors,interests,created_at FROM family_members WHERE household_id='family' ORDER BY created_at").all()).results);
  if(method==='POST'){const x=await parse(request),name=safe(x.name,60);if(!name)return error('Cần tên thành viên.');const count=await env.DB.prepare("SELECT COUNT(*) AS n FROM family_members WHERE household_id='family'").first();if(count.n>=20)return error('Tối đa 20 thành viên.');const row={id:crypto.randomUUID(),name,avatar_key:safe(x.avatar_key,50),favorite_colors:safe(x.favorite_colors,200),interests:safe(x.interests,500),created_at:Date.now()};await env.DB.prepare('INSERT INTO family_members(id,household_id,name,avatar_key,favorite_colors,interests,created_at) VALUES(?,\'family\',?,?,?,?,?)').bind(row.id,row.name,row.avatar_key,row.favorite_colors,row.interests,row.created_at).run();return json(row,201)}
  if(method==='PATCH'){const x=await parse(request),id=safe(x.id,80),name=safe(x.name,60);if(!id||!name)return error('Thiếu tên hoặc mã thành viên.');const result=await env.DB.prepare("UPDATE family_members SET name=?,avatar_key=?,favorite_colors=?,interests=? WHERE id=? AND household_id='family'").bind(name,safe(x.avatar_key,50),safe(x.favorite_colors,200),safe(x.interests,500),id).run();return result.meta.changes?json({ok:true}):error('Không tìm thấy thành viên.',404)}
  if(method==='DELETE'){const id=new URL(request.url).searchParams.get('id');if(!id)return error('Thiếu mã thành viên.');await env.DB.prepare("DELETE FROM family_members WHERE id=? AND household_id='family'").bind(id).run();return json({ok:true})}return error('Phương thức không hỗ trợ.',405)}
 if(path==='/api/offers'){
  if(method==='GET')return json((await env.DB.prepare("SELECT * FROM price_offers WHERE household_id='family' ORDER BY observed_at DESC LIMIT 500").all()).results);
  if(method==='POST'){const x=await parse(request),product=safe(x.product,120),store=safe(x.store,80),price=Number(x.price),regular=x.regular_price===''||x.regular_price==null?null:Number(x.regular_price),url=safe(x.url,500);if(!product||!store||!Number.isFinite(price)||price<=0||regular!==null&&(!Number.isFinite(regular)||regular<=0))return error('Sản phẩm, cửa hàng hoặc giá không hợp lệ.');if(url&&!/^https:\/\//i.test(url))return error('Chỉ nhận liên kết HTTPS.');const row={id:crypto.randomUUID(),product,store,price,regular_price:regular,size_label:safe(x.size_label,40),url,expiry_date:safe(x.expiry_date,10),observed_at:new Date().toISOString().slice(0,10),note:safe(x.note,500),created_at:Date.now()};await env.DB.prepare("INSERT INTO price_offers(id,household_id,product,store,price,regular_price,size_label,url,expiry_date,observed_at,note,created_at) VALUES(?,'family',?,?,?,?,?,?,?,?,?,?)").bind(...Object.values(row)).run();return json(row,201)}
  if(method==='DELETE'){const id=new URL(request.url).searchParams.get('id');if(!id)return error('Thiếu mã giá.');await env.DB.prepare("DELETE FROM price_offers WHERE id=? AND household_id='family'").bind(id).run();return json({ok:true})}return error('Phương thức không hỗ trợ.',405)}
 if(path==='/api/offers/feed'&&method==='GET'){
  if(!env.SALES_FEED_URL)return json({items:[],configured:false});
  const response=await fetch(env.SALES_FEED_URL,{headers:env.SALES_FEED_TOKEN?{Authorization:`Bearer ${env.SALES_FEED_TOKEN}`}:{}});if(!response.ok)return error('Nguồn giá chưa phản hồi.',502);const body=await response.json();if(!Array.isArray(body.items))return error('Định dạng nguồn giá không hợp lệ.',502);return json({configured:true,items:body.items.slice(0,200).map(x=>({product:safe(x.product,120),store:safe(x.store,80),price:Number(x.price),regular_price:x.regular_price==null?null:Number(x.regular_price),size_label:safe(x.size_label,40),url:/^https:\/\//.test(x.url||'')?safe(x.url,500):'',expiry_date:safe(x.expiry_date,10),observed_at:safe(x.observed_at,10)})).filter(x=>x.product&&x.store&&Number.isFinite(x.price)&&x.price>0)})}
 return null}
export async function handlePublicFeedback(request,env){if(request.method!=='POST')return error('Phương thức không hỗ trợ.',405);if(request.headers.get('origin')!==new URL(request.url).origin)return error('Yêu cầu không hợp lệ.',403);const x=await parse(request);if(x.website)return json({ok:true});const message=safe(x.message,2000),contact=safe(x.contact,120);if(message.length<10)return error('Vui lòng viết ít nhất 10 ký tự.');const rawIp=request.headers.get('cf-connecting-ip')||'unknown',ipBytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(rawIp+'|'+(env.FEEDBACK_SALT||'family-hub'))),visitorHash=Array.from(new Uint8Array(ipBytes),b=>b.toString(16).padStart(2,'0')).join('');const recent=await env.DB.prepare('SELECT COUNT(*) AS n FROM feedback WHERE visitor_hash=? AND created_at>?').bind(visitorHash,Date.now()-86400000).first();if(recent.n>=3)return error('Bạn đã gửi đủ góp ý hôm nay. Cảm ơn bạn!',429);await env.DB.prepare('INSERT INTO feedback(id,contact,message,created_at,visitor_hash) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),contact,message,Date.now(),visitorHash).run();return json({ok:true},201)}
