import React,{useState} from 'react';
import {Camera,Trash2,Pencil,X,Plus} from 'lucide-react';
import {t} from './i18n.js';
const initial=()=>({title:'',note:'',person:'Cả nhà',date:new Date().toISOString().slice(0,10),photos:[]});
function photosOf(entry){try{const parsed=JSON.parse(entry.details||'{}');return Array.isArray(parsed.photos)?parsed.photos.filter(x=>/^[a-f0-9-]{36}$/.test(x)).slice(0,6):entry.image_key?[entry.image_key]:[]}catch{return entry.image_key?[entry.image_key]:[]}}
export default function Diary({items,setItems,people,api,lang,onError}){
 const [editor,setEditor]=useState(null),[draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[open,setOpen]=useState(null),[message,setMessage]=useState('');
 const tr=x=>t(x,lang),posts=items.filter(x=>x.kind==='diary').sort((a,b)=>(b.date||'').localeCompare(a.date||'')||b.created_at-a.created_at);
 function write(post){setEditor(post?.id||'new');setDraft(post?{title:post.title,note:post.note||'',person:post.person,date:post.date||'',photos:photosOf(post)}:initial());setMessage('')}
 async function upload(files){const available=6-draft.photos.length;if(files.length>available){setMessage(tr('Tối đa 6 ảnh cho mỗi bài viết.'));return}setBusy(true);setMessage('');try{const keys=[];for(const file of files){const data=new FormData();data.append('file',file);const result=await api('/photos',{method:'POST',body:data});keys.push(result.key)}setDraft(x=>({...x,photos:[...x.photos,...keys]}))}catch(err){setMessage(err.message)}finally{setBusy(false)}}
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{const payload={title:draft.title.trim(),note:draft.note,person:draft.person,date:draft.date,image_key:draft.photos[0]||'',details:JSON.stringify({photos:draft.photos})};if(!payload.title||!payload.note.trim())throw Error(tr('Viết tiêu đề và nội dung nhật ký.'));if(editor==='new'){const row=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,kind:'diary'})});setItems(xs=>[row,...xs])}else{await api('/records',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,id:editor})});setItems(xs=>xs.map(x=>x.id===editor?{...x,...payload}:x));setOpen(editor)}setEditor(null)}catch(err){setMessage(err.message)}finally{setBusy(false)}}
 async function remove(post){if(!confirm(tr('Xóa bài nhật ký này?')))return;try{await api('/records?id='+encodeURIComponent(post.id),{method:'DELETE'});setItems(xs=>xs.filter(x=>x.id!==post.id));setOpen(null)}catch(err){onError(err.message)}}
 return <div className="diary-page"><div className="diary-intro"><div><h2>{tr('Chuyện nhà mình')}</h2><p>{tr('Viết lại những ngày đáng nhớ, thêm ảnh và cùng xem lại sau này.')}</p></div><button className="primary" onClick={()=>write()}><Plus size={16}/>{tr('Viết bài mới')}</button></div>
  {posts.length?<div className="diary-grid">{posts.map(post=>{const photos=photosOf(post);return <article className="diary-card" key={post.id}><button className="diary-cover" onClick={()=>setOpen(post.id)} aria-label={tr('Đọc bài')+' '+post.title}>{photos.length?<img src={'/api/photos/'+photos[0]} alt="" loading="lazy"/>:<span>✦</span>}</button><div className="diary-card-copy"><small>{post.date} · {tr(post.person)}{photos.length?' · '+photos.length+' '+tr('ảnh'):''}</small><h3>{post.title}</h3><p>{post.note}</p><button className="text-btn" onClick={()=>setOpen(post.id)}>{tr('Đọc bài')} →</button></div></article>})}</div>:<div className="panel diary-empty"><Camera size={31}/><p>{tr('Chưa có bài nhật ký. Hãy lưu lại một khoảnh khắc của nhà mình.')}</p><button className="text-btn" onClick={()=>write()}>{tr('Viết bài đầu tiên')}</button></div>}
  {open&&(()=>{const post=posts.find(x=>x.id===open);if(!post)return null;return <div className="modal-backdrop" onClick={()=>setOpen(null)}><article className="modal diary-reader" role="dialog" aria-modal="true" aria-label={post.title} onClick={e=>e.stopPropagation()}><div className="modal-head"><small>{post.date} · {tr(post.person)}</small><button onClick={()=>setOpen(null)} aria-label={tr('Đóng')}><X/></button></div><h2>{post.title}</h2><div className="diary-body">{post.note}</div><div className="diary-photos">{photosOf(post).map((key,i)=><a key={key} href={'/api/photos/'+key} target="_blank" rel="noopener noreferrer"><img src={'/api/photos/'+key} alt={post.title+' '+(i+1)} loading="lazy"/></a>)}</div><div className="diary-actions"><button className="text-btn" onClick={()=>{setOpen(null);write(post)}}><Pencil size={16}/>{tr('Sửa')}</button><button className="text-btn" onClick={()=>remove(post)}><Trash2 size={16}/>{tr('Xóa')}</button></div></article></div>})()}
  {editor&&<div className="modal-backdrop" onClick={()=>!busy&&setEditor(null)}><div className="modal form-dialog diary-editor" role="dialog" aria-modal="true" aria-label={tr('Viết nhật ký')} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{tr('Viết nhật ký')}</h2><button onClick={()=>setEditor(null)} aria-label={tr('Đóng')}><X/></button></div><form className="entry-form" onSubmit={save}><label className="field"><span>{tr('Tiêu đề *')}</span><input required maxLength="180" value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))} placeholder={tr('Một ngày đáng nhớ…')}/></label><div className="form-row"><label className="field"><span>{tr('Người viết')}</span><select value={draft.person} onChange={e=>setDraft(x=>({...x,person:e.target.value}))}>{people.map(x=><option key={x} value={x}>{tr(x)}</option>)}</select></label><label className="field"><span>{tr('Ngày')}</span><input required type="date" value={draft.date} onChange={e=>setDraft(x=>({...x,date:e.target.value}))}/></label></div><label className="field"><span>{tr('Câu chuyện của nhà mình *')}</span><textarea required rows="9" maxLength="12000" value={draft.note} onChange={e=>setDraft(x=>({...x,note:e.target.value}))} placeholder={tr('Hôm nay nhà mình…')}/></label><label className="upload"><Camera size={18}/>{tr('Thêm ảnh (JPEG, PNG, WebP; tối đa 6 ảnh)')}<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.length)upload([...e.target.files]);e.target.value=''}} disabled={busy||draft.photos.length>=6}/></label><div className="diary-preview">{draft.photos.map(key=><div key={key}><img src={'/api/photos/'+key} alt=""/><button type="button" onClick={()=>setDraft(x=>({...x,photos:x.photos.filter(p=>p!==key)}))} aria-label={tr('Xóa ảnh')}><X size={15}/></button></div>)}</div>{message&&<p className="form-error" role="alert">{message}</p>}<button className="primary submit" disabled={busy}>{tr(busy?'Đang lưu…':'Đăng bài')}</button></form></div></div>}
 </div>
}
