import React,{useState} from 'react';
import {Settings2,Coins,Wallet,Users,Tags} from 'lucide-react';
import {icons,iconFor} from './IconPicker.jsx';
import {detailsOf,expandRecords,nextOccurrences} from './recurrence.js';
import {t} from './i18n.js';
const fmt=n=>new Intl.NumberFormat('da-DK',{style:'currency',currency:'DKK',maximumFractionDigits:0}).format(n||0);
export default function FinanceView({items,people,jars,lang,month,onSettings}){
 const [group,setGroup]=useState('category'),tr=x=>t(x,lang);
 const first=month+'-01',last=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10);
 const expenses=expandRecords(items,first,last,['expense']),incomes=expandRecords(items,first,last,['income']);
 const income=incomes.reduce((a,x)=>a+Number(x.amount||0),0),spent=expenses.reduce((a,x)=>a+Number(x.amount||0),0);
 const categories=expenses.reduce((a,x)=>{const key=group==='person'?x.person:x.category||tr('Khác');const slot=a[key]||{amount:0,icon:iconFor(x)};slot.amount+=Number(x.amount||0);a[key]=slot;return a},{});
 if(group==='person')for(const person of people)categories[person]??={amount:0,icon:Users};
 const chart=Object.entries(categories).sort((a,b)=>b[1].amount-a[1].amount);
 const coming=nextOccurrences(items,new Date().toISOString().slice(0,10),new Date(Date.now()+365*86400000).toISOString().slice(0,10),['tax','saving']).slice(0,8);
 return <><div className="metrics"><div><span>{tr('Thu nhập tháng')}</span><strong>{fmt(income)}</strong></div><div><span>{tr('Đã chi tháng')}</span><strong>{fmt(spent)}</strong></div><div><span>{tr('Chênh lệch')}</span><strong>{fmt(income-spent)}</strong></div><div><span>{tr('Claim chờ nhận')}</span><strong>{fmt(items.filter(x=>x.kind==='claim'&&x.status!=='done').reduce((a,x)=>a+Number(x.amount||0),0))}</strong></div></div>
  <section className="panel money-jars"><div className="panel-head"><div><h2>{tr('Hũ tài chính của nhà mình')}</h2><p>{tr('Đồng tiền thể hiện số còn lại sau chi tiêu so với kế hoạch tháng này.')}</p></div><button className="text-btn" onClick={onSettings}><Settings2 size={17}/>{tr('Thiết kế hũ')}</button></div><div className="money-jars-grid">{jars.map(jar=>{const plan=income*Number(jar.percent||0)/100;const used=expenses.filter(x=>{const d=detailsOf(x);return d.jar_id===jar.id||(!d.jar_id&&x.category?.toLowerCase()===jar.name.toLowerCase())}).reduce((a,x)=>a+Number(x.amount||0),0);const remaining=plan-used,level=plan>0?Math.min(1,Math.max(0,remaining/plan)):0,Icon=icons[jar.color?.startsWith('icon:')?jar.color.slice(5):'money']||Wallet;return <article className={'money-jar'+(remaining<0?' overdrawn':'')} key={jar.id}><div className="jar-glass" aria-label={jar.name+' '+fmt(remaining)}><div className="jar-lid"/><div className="jar-body"><div className="jar-coins" style={{height:Math.max(0,level*78)+'%'}}>{Array.from({length:Math.max(0,Math.min(10,Math.round(level*10)))},(_,i)=><Coins key={i} size={22}/>)}</div><Icon className="jar-symbol" size={28}/></div></div><strong>{jar.name}</strong><small>{jar.percent}% · {tr('Kế hoạch')} {fmt(plan)}</small><b>{tr('Còn lại')} {fmt(remaining)}</b><small>{tr('Đã chi')} {fmt(used)}</small></article>})}</div>{!jars.length&&<p className="hint">{tr('Chưa có hũ tài chính.')}</p>}</section>
  <section className="panel spending-chart"><div className="panel-head"><div><h2>{tr('Biểu đồ chi tiêu')}</h2><p>{tr('Chọn cách nhóm các khoản chi trong tháng.')}</p></div><div className="chart-toggle"><button className={group==='category'?'selected':''} onClick={()=>setGroup('category')}><Tags size={16}/>{tr('Theo nhóm')}</button><button className={group==='person'?'selected':''} onClick={()=>setGroup('person')}><Users size={16}/>{tr('Theo người')}</button></div></div>{chart.some(([,d])=>d.amount>0)?<div className="spending-bars">{chart.map(([name,data])=>{const Icon=data.icon;return <div className="spending-bar" key={name}><span><Icon size={18}/>{tr(name)}</span><div className="spending-track"><div style={{width:Math.max(2,data.amount/(spent||1)*100)+'%'}}/></div><strong>{fmt(data.amount)}</strong></div>})}</div>:<p className="hint">{tr('Chưa ghi khoản chi tháng này.')}</p>}</section>
  <section className="panel recurring-upcoming"><div className="panel-head"><h2>{tr('Thuế & tiết kiệm sắp tới')}</h2></div>{coming.length?coming.map(x=>{const Icon=iconFor(x);return <div className="recurring-upcoming-row" key={x.id}><Icon size={18}/><strong>{x.title}</strong><small>{x.date}{x.recurring?' · ↻':''}</small><b>{fmt(x.amount)}</b></div>}):<p className="hint">{tr('Chưa có kỳ thuế hoặc tiết kiệm sắp tới.')}</p>}</section>
  </>
}
