import React,{useEffect,useState} from 'react';
import {UtensilsCrossed,Plus,ArrowRight,Trash2,Activity,Settings2} from 'lucide-react';
import {detailsOf,withDetails} from './recurrence.js';
import {nutritionKeys,nutritionUnits,sumMealLogs} from './nutrition.js';
import {nutritionForRecipe} from './nutrition.js';
import {t} from './i18n.js';
const labels={kcal:'Năng lượng',protein:'Đạm',fat:'Chất béo',carbs:'Tinh bột',fiber:'Chất xơ',sodium:'Natri'};
const today=()=>new Date().toISOString().slice(0,10);
const num=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(n);
export default function HealthNutrition({items,setItems,api,people,selectedPerson,lang,onError,onLog,onKitchen,onActivity,remove}){
 const tr=x=>t(x,lang),[chosen,setChosen]=useState(people.find(x=>x!=='Cả nhà')||'Mẹ'),[date,setDate]=useState(today),[editing,setEditing]=useState(false),[draft,setDraft]=useState({}),[busy,setBusy]=useState(false);
 useEffect(()=>{if(selectedPerson!=='Tất cả'&&selectedPerson!=='Cả nhà')setChosen(selectedPerson)},[selectedPerson]);
 const person=selectedPerson!=='Tất cả'&&selectedPerson!=='Cả nhà'?selectedPerson:chosen,child=/^shin$/i.test(person);
 const logs=items.filter(x=>x.kind==='meal_log'&&x.person===person&&x.date===date).sort((a,b)=>(a.created_at||0)-(b.created_at||0));
 const activities=items.filter(x=>x.kind==='health'&&x.person===person&&x.date===date&&x.category==='Vận động');
 const {total,coverage}=sumMealLogs(logs),targetRow=items.filter(x=>x.kind==='health'&&x.person===person&&x.category==='Mục tiêu dinh dưỡng').sort((a,b)=>(b.created_at||0)-(a.created_at||0))[0],target=detailsOf(targetRow||{}).nutritionTarget||{};
 useEffect(()=>setDraft(target),[targetRow?.id,person]);
 const last7=Array.from({length:7},(_,index)=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-6+index);const key=d.toISOString().slice(0,10),days=items.filter(x=>x.kind==='meal_log'&&x.person===person&&x.date===key),sum=sumMealLogs(days);return {key,count:days.length,kcal:sum.total.kcal,known:sum.coverage.kcal===days.length&&days.length>0}});
 const max=Math.max(1,...last7.map(x=>x.kcal));
 async function saveTarget(e){e.preventDefault();const values={};for(const k of nutritionKeys){if(draft[k]===''||draft[k]==null)continue;const v=Number(draft[k]);if(!Number.isFinite(v)||v<=0||v>100000){onError(tr('Mục tiêu phải là số dương.'));return}values[k]=v}if(!Object.keys(values).length){onError(tr('Hãy nhập ít nhất một mục tiêu.'));return}setBusy(true);try{if(targetRow){const details=withDetails(targetRow,{nutritionTarget:values});await api('/records',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:targetRow.id,details})});setItems(rows=>rows.map(x=>x.id===targetRow.id?{...x,details}:x))}else{const row=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'health',title:'Mục tiêu dinh dưỡng – '+person,category:'Mục tiêu dinh dưỡng',person,date:today(),details:JSON.stringify({nutritionTarget:values})})});setItems(rows=>[row,...rows])}setEditing(false)}catch(err){onError(err.message)}finally{setBusy(false)}}
 const complete=key=>logs.length>0&&coverage[key]===logs.length;
 const suggested=items.filter(x=>x.kind==='meal').map(x=>({title:x.title,nutrition:nutritionForRecipe(x,items).nutrition})).filter(x=>x.nutrition).sort((a,b)=>b.nutrition.protein-a.nutrition.protein).slice(0,2);
 return <section className="panel nutrition-dashboard"><div className="panel-head"><div><h2><UtensilsCrossed size={22}/>{tr('Nhật ký ăn uống')}</h2><p>{tr('Bữa ăn từ Bếp được ghi theo ngày và theo từng thành viên.')}</p></div><div className="nutrition-actions"><button className="text-btn" onClick={onKitchen}>{tr('Xem bếp')} <ArrowRight size={16}/></button><button className="primary" onClick={()=>onLog(null,person)}><Plus size={16}/>{tr('Ghi bữa ăn')}</button></div></div>
  <div className="nutrition-filters"><label>{tr('Người ăn')} <select value={person} onChange={e=>setChosen(e.target.value)} disabled={selectedPerson!=='Tất cả'}>{people.filter(x=>x!=='Cả nhà').map(x=><option key={x} value={x}>{tr(x)}</option>)}</select></label><label>{tr('Ngày ăn')} <input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label>{!child&&<button className="text-btn" onClick={()=>setEditing(x=>!x)}><Settings2 size={16}/>{tr('Mục tiêu cá nhân')}</button>}</div>
  {editing&&!child&&<form className="nutrition-target-editor" onSubmit={saveTarget}><p>{tr('Nhập mục tiêu do bạn tự đặt hoặc được chuyên gia tư vấn; Cura không tự kê khẩu phần.')}</p><div className="nutrition-fields">{nutritionKeys.map(key=><label className="field" key={key}><span>{tr(labels[key])} ({nutritionUnits[key]})</span><input type="number" min="0.01" step="0.01" value={draft[key]??''} onChange={e=>setDraft(v=>({...v,[key]:e.target.value}))}/></label>)}</div><button className="primary" disabled={busy}>{tr('Lưu mục tiêu')}</button></form>}
  {child&&<div className="nutrition-advice"><Activity size={18}/>{tr('Với trẻ em, Cura chỉ ghi lại bữa ăn; không tự chấm thiếu/thừa calories hoặc đưa mục tiêu giảm cân.')}</div>}
  <div className="nutrition-summary">{nutritionKeys.map(key=>{const known=complete(key),goal=Number(target[key]),hasGoal=!child&&Number.isFinite(goal)&&goal>0;return <div className="nutrition-metric" key={key}><span>{tr(labels[key])}</span><strong>{coverage[key]?num(total[key]):'—'} <small>{nutritionUnits[key]}</small></strong><small>{logs.length?tr('Có dữ liệu')+' '+coverage[key]+'/'+logs.length+' '+tr('bữa'):tr('Chưa ghi bữa nào')}{hasGoal?' · '+tr('Mục tiêu')+' '+num(goal):''}</small>{hasGoal&&known&&<div className="nutrition-progress"><span style={{width:Math.min(100,total[key]/goal*100)+'%'}}/></div>}</div>})}</div>
  {!child&&logs.length>0&&Object.keys(target).length>0&&<div className="nutrition-advice">{nutritionKeys.filter(k=>target[k]>0&&complete(k)&&Math.abs(total[k]-target[k])/target[k]>.1).map(k=><p key={k}>{tr(labels[k])}: {num(total[k])} / {num(target[k])} {nutritionUnits[k]} · {total[k]>target[k]?tr('cao hơn mục tiêu đã đặt'):tr('thấp hơn mục tiêu đã đặt')}.</p>)}{nutritionKeys.some(k=>coverage[k]<logs.length)&&<p>{tr('Một số bữa chưa đủ dữ liệu, vì vậy chưa thể kết luận mức thừa/thiếu.')}</p>}{complete('protein')&&target.protein>0&&total.protein<target.protein*.9&&suggested.length>0&&<p>{tr('Công thức có đạm đã lưu để tham khảo')}: {suggested.map(x=>x.title).join(', ')}.</p>}{complete('kcal')&&target.kcal>0&&total.kcal>target.kcal*1.1&&<p>{tr('Có thể xem lại khẩu phần bữa sau và chọn vận động phù hợp; Cura không quy đổi thức ăn thành bài tập.')}</p>}<button className="text-btn" onClick={onKitchen}>{tr('Xem công thức và điều chỉnh bữa sau')} <ArrowRight size={15}/></button></div>}
  <div className="nutrition-history"><div><h3>{tr('Bữa ăn ngày này')}</h3>{logs.length?logs.map(x=><div className="meal-log-row" key={x.id}>{x.image_key&&<img src={'/api/photos/'+x.image_key} alt=""/>}<div><strong>{x.title}</strong><small>{tr(x.category||'Bữa ăn')} · {detailsOf(x).servings||1} {tr('suất')}{detailsOf(x).nutrition?.kcal!=null?' · '+num(detailsOf(x).nutrition.kcal)+' kcal':''}</small></div><button title={tr('Xóa')} onClick={()=>remove(x)}><Trash2 size={16}/></button></div>):<p className="hint">{tr('Chưa ghi bữa ăn nào trong ngày này.')}</p>}<div className="activity-head"><h3>{tr('Vận động đã ghi')}</h3><button className="text-btn" onClick={()=>onActivity(person,date)}><Plus size={15}/>{tr('Ghi vận động')}</button></div>{activities.length?activities.map(x=><p className="small-note" key={x.id}>{x.title} · {x.quantity||'—'} {x.unit||tr('phút')}</p>):<p className="small-note">{tr('Chưa ghi vận động ngày này.')}</p>}</div><div><h3>{tr('Năng lượng đã ghi trong 7 ngày')}</h3><div className="nutrition-week">{last7.map(day=><div className="nutrition-day" key={day.key} title={day.key+' · '+(day.known?num(day.kcal)+' kcal':tr('Chưa đủ dữ liệu'))}><div className="nutrition-day-track"><span style={{height:day.known?Math.max(6,day.kcal/max*100)+'%':'0%'}}/></div><small>{day.key.slice(8)}</small></div>)}</div><p className="small-note">{tr('Ngày không có dữ liệu được để trống; biểu đồ không tự điền số 0.')}</p></div></div>
  <p className="small-note">{tr('Dinh dưỡng từ công thức chỉ là ước tính theo lượng nguyên liệu đã nhập; cách chế biến và khẩu phần thực tế có thể khác.')}</p>
 </section>
}
