import React,{useState} from 'react';
import {ChefHat,Plus,Trash2,Camera,DoorOpen,ShoppingBasket,ChevronLeft,ChevronRight,X,Refrigerator} from 'lucide-react';
import {detailsOf} from './recurrence.js';
import {t} from './i18n.js';
const today=()=>new Date().toISOString().slice(0,10);
const groups=[['shelf','Kệ đồ khô','🍜'],['fresh','Ngăn thực phẩm tươi','🥩'],['vegetables','Rau củ','🥬'],['fruit','Hoa quả','🍎'],['frozen','Tủ đông','🧊']];
function groupOf(food){const cat=(food.category||'').toLowerCase();if(/đông|frozen|freezer/.test(cat))return 'frozen';if(/rau|củ|vegetable/.test(cat))return 'vegetables';if(/hoa quả|trái cây|fruit/.test(cat))return 'fruit';if(/tươi|thịt|cá|fresh|meat/.test(cat))return 'fresh';return 'shelf'}
const emoji=name=>/phở|mì|noodle|pasta/i.test(name)?'🍝':/quế|hồi|spice|gia vị/i.test(name)?'🧂':/bò|beef/i.test(name)?'🥩':/cá|fish/i.test(name)?'🐟':/gà|chicken/i.test(name)?'🍗':/cà|tomat/i.test(name)?'🍅':/rau|salad/i.test(name)?'🥬':/quả|apple|táo/i.test(name)?'🍎':'🥫';
const blank=()=>({title:'',person:'Cả nhà',category:'Bữa tối',ingredients:[{name:'',quantity:'',unit:'',image_key:''}],steps:[{text:'',image_key:''}],image_key:''});
export default function Kitchen({items,setItems,api,lang,add,update,remove,onError}){
 const tr=x=>t(x,lang),[open,setOpen]=useState({fresh:false,frozen:false}),[recipe,setRecipe]=useState(null),[draft,setDraft]=useState(blank),[saving,setSaving]=useState(false),[active,setActive]=useState(null),[feedback,setFeedback]=useState('');
 const stock=items.filter(x=>x.kind==='food'),recipes=items.filter(x=>x.kind==='meal');
 const available=item=>Number(item.quantity??1)>0&&(!item.date||item.date>=today());
 const matches=name=>stock.find(s=>available(s)&&(s.title.toLocaleLowerCase().includes(name.trim().toLocaleLowerCase())||name.trim().toLocaleLowerCase().includes(s.title.toLocaleLowerCase())));
 async function buy(name){if(!name.trim()||items.some(x=>x.kind==='shopping'&&x.status!=='done'&&x.title.toLocaleLowerCase()===name.toLocaleLowerCase())){setFeedback(tr('Món này đã có trong danh sách cần mua.'));return}try{const row=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'shopping',title:name,category:'Thực phẩm',person:'Cả nhà'})});setItems(xs=>[row,...xs]);setFeedback(tr('Đã thêm vào danh sách cần mua.'))}catch(e){onError(e.message)}}
 function editRecipe(x){const data=x?detailsOf(x):blank();setDraft({title:x?.title||'',person:x?.person||'Cả nhà',category:x?.category||'Bữa tối',image_key:x?.image_key||'',ingredients:data.ingredients?.length?data.ingredients:[{name:'',quantity:'',unit:'',image_key:''}],steps:data.steps?.length?data.steps:[{text:'',image_key:''}]});setRecipe(x?.id||'new');setFeedback('')}
 function changeList(key,index,patch){setDraft(d=>({...d,[key]:d[key].map((entry,i)=>i===index?{...entry,...patch}:entry)}))}
 async function upload(file,key,index){setSaving(true);try{const fd=new FormData();fd.append('file',file);const result=await api('/photos',{method:'POST',body:fd});if(key==='image_key')setDraft(d=>({...d,image_key:result.key}));else changeList(key,index,{image_key:result.key})}catch(e){setFeedback(e.message)}finally{setSaving(false)}}
 async function save(e){e.preventDefault();setSaving(true);try{const ingredients=draft.ingredients.filter(x=>x.name.trim()),steps=draft.steps.filter(x=>x.text.trim());if(!ingredients.length||!steps.length)throw Error(tr('Thêm ít nhất một nguyên liệu và một bước nấu.'));const data={title:draft.title,category:draft.category,person:draft.person,image_key:draft.image_key,kind:'meal',note:ingredients.map(x=>x.name).join(', '),details:JSON.stringify({ingredients,steps})};if(recipe==='new'){const row=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});setItems(xs=>[row,...xs])}else{await api('/records',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...data,id:recipe})});setItems(xs=>xs.map(x=>x.id===recipe?{...x,...data}:x))}setRecipe(null)}catch(e){setFeedback(e.message)}finally{setSaving(false)}}
 const showIngredients=x=>{const d=detailsOf(x);return d.ingredients?.length?d.ingredients:x.note?.replace(/^nguyên liệu\s*:/i,'').split(',').map(name=>({name:name.trim()})).filter(x=>x.name)||[]};
 return <div className="kitchen-page"><div className="panel-head"><div><h2>{tr('Kho thực phẩm nhà mình')}</h2><p>{tr('Chạm vào tủ để mở; rê chuột hoặc chạm món đồ để xem số lượng còn.')}</p></div><button className="text-btn" onClick={()=>add('food')}><Plus size={16}/>{tr('Nhập thực phẩm')}</button></div>
 <div className="kitchen-scene">{groups.map(([key,label,pict])=>{const content=stock.filter(x=>groupOf(x)===key),closed=['fresh','frozen'].includes(key)&&!open[key];return <section className={'pantry-unit '+key} key={key}><button className="pantry-header" type="button" onClick={()=>['fresh','frozen'].includes(key)&&setOpen(o=>({...o,[key]:!o[key]}))}><span>{pict}</span><strong>{tr(label)}</strong><small>{content.length} {tr('món')}</small>{['fresh','frozen'].includes(key)&&<DoorOpen size={19}/>}</button><div className={'pantry-interior'+(closed?' closed':'')}><div className="pantry-items">{content.length?content.map(item=><article className={'pantry-item'+(!available(item)?' empty-stock':'')} key={item.id} title={item.title+' · '+(item.quantity??tr('chưa ghi số lượng'))+' '+(item.unit||'')}><div className="pantry-image">{item.image_key?<img src={'/api/photos/'+item.image_key} alt=""/>:<span aria-hidden="true">{emoji(item.title)}</span>}</div><strong>{item.title}</strong><small>{available(item)?(item.quantity??'—')+' '+(item.unit||''):tr('Hết hàng')}</small><div className="pantry-actions">{!available(item)?<button onClick={()=>buy(item.title)} title={tr('Thêm vào danh sách cần mua')}><ShoppingBasket size={15}/></button>:<button onClick={()=>update(item,{quantity:Math.max(0,Number(item.quantity??1)-1)})} title={tr('Dùng một')}>−</button>}<button onClick={()=>remove(item)} title={tr('Xóa')}><Trash2 size={14}/></button></div></article>):<p className="hint">{tr('Kệ này chưa có món nào.')}</p>}</div></div>{closed&&<button className="pantry-door" onClick={()=>setOpen(o=>({...o,[key]:true}))} aria-label={tr('Mở tủ')+' '+tr(label)}><Refrigerator size={58}/><span>{tr('Chạm để mở')}</span></button>}</section>})}</div>
 <div className="panel-head kitchen-recipes-head"><div><h2>{tr('Sổ món nhà mình')}</h2><p>{tr('Nguyên liệu có sẵn sáng lên; nguyên liệu thiếu sẽ hiện mờ.')}</p></div><button className="primary" onClick={()=>editRecipe()}><ChefHat size={17}/>{tr('Thêm công thức')}</button></div>
 <div className="recipe-grid">{recipes.map(x=>{const ingredients=showIngredients(x);return <article className="recipe-tile" key={x.id}><button className="recipe-cover" onClick={()=>setActive(x.id)}>{x.image_key?<img src={'/api/photos/'+x.image_key} alt=""/>:<span>🍲</span>}</button><div className="recipe-copy"><small>{x.category||tr('Món nhà hay ăn')}</small><h3>{x.title}</h3><p>{ingredients.filter(y=>matches(y.name)).length}/{ingredients.length} {tr('nguyên liệu sẵn có')}</p><button className="text-btn" onClick={()=>setActive(x.id)}>{tr('Xem công thức')} →</button></div></article>})}</div>
 {feedback&&<p role="status" className="kitchen-feedback">{feedback}</p>}
 {active&&(()=>{const x=recipes.find(r=>r.id===active);if(!x)return null;const d=detailsOf(x),ingredients=showIngredients(x);return <div className="modal-backdrop" onClick={()=>setActive(null)}><article className="modal recipe-reader" role="dialog" aria-modal="true" aria-label={x.title} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{x.title}</h2><button onClick={()=>setActive(null)} aria-label={tr('Đóng')}><X/></button></div><h3>{tr('Nguyên liệu')}</h3><div className="recipe-ingredients">{ingredients.map((part,i)=>{const found=matches(part.name);return <div className={'ingredient '+(found?'available':'missing')} key={i}>{part.image_key?<img src={'/api/photos/'+part.image_key} alt=""/>:<span>{emoji(part.name)}</span>}<strong>{part.name}</strong><small>{part.quantity} {part.unit} · {found?tr('Có sẵn')+' '+(found.quantity??'')+' '+(found.unit||''):tr('Cần mua')}</small>{!found&&<button onClick={()=>buy(part.name)} aria-label={tr('Thêm vào danh sách cần mua')+' '+part.name}><Plus size={16}/></button>}</div>})}</div><div className="inline-actions"><button className="text-btn" onClick={()=>ingredients.filter(p=>!matches(p.name)).forEach(p=>buy(p.name))}><ShoppingBasket size={16}/>{tr('Thêm tất cả món thiếu vào danh sách mua')}</button></div><h3>{tr('Cách làm')}</h3>{(d.steps||[]).map((step,i)=><div className="recipe-step" key={i}><b>{i+1}</b><p>{step.text}</p>{step.image_key&&<img src={'/api/photos/'+step.image_key} alt={tr('Bước')+' '+(i+1)}/>}</div>)}{!d.steps?.length&&<p>{tr('Chưa ghi cách làm.')}</p>}<div className="inline-actions"><button className="text-btn" onClick={()=>{setActive(null);editRecipe(x)}}>{tr('Sửa công thức')}</button><button className="text-btn" onClick={()=>{setActive(null);remove(x)}}>{tr('Xóa')}</button></div></article></div>})()}
 {recipe&&<div className="modal-backdrop" onClick={()=>!saving&&setRecipe(null)}><div className="modal form-dialog recipe-editor" role="dialog" aria-modal="true" aria-label={tr('Công thức nấu ăn')} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{tr('Công thức nấu ăn')}</h2><button onClick={()=>setRecipe(null)} aria-label={tr('Đóng')}><X/></button></div><form className="entry-form" onSubmit={save}><label className="field"><span>{tr('Tên món ăn')} *</span><input required value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></label><label className="upload"><Camera size={16}/>{tr('Ảnh món ăn')}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'image_key')}/></label><h3>{tr('Nguyên liệu')}</h3>{draft.ingredients.map((part,i)=><div className="recipe-entry" key={i}><input required placeholder={tr('Tên nguyên liệu')} value={part.name} onChange={e=>changeList('ingredients',i,{name:e.target.value})}/><input type="number" min="0" step="0.01" placeholder={tr('Số lượng')} value={part.quantity} onChange={e=>changeList('ingredients',i,{quantity:e.target.value})}/><input placeholder={tr('Đơn vị')} value={part.unit} onChange={e=>changeList('ingredients',i,{unit:e.target.value})}/><label className="tiny-upload" title={tr('Thêm ảnh')}><Camera size={18}/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'ingredients',i)}/></label><button type="button" onClick={()=>setDraft(d=>({...d,ingredients:d.ingredients.filter((_,n)=>i!==n)}))}><Trash2 size={16}/></button>{part.image_key&&<img src={'/api/photos/'+part.image_key} alt=""/>}</div>)}<button type="button" className="text-btn" onClick={()=>setDraft(d=>({...d,ingredients:[...d.ingredients,{name:'',quantity:'',unit:'',image_key:''}]}))}><Plus size={16}/>{tr('Thêm nguyên liệu')}</button><h3>{tr('Cách làm từng bước')}</h3>{draft.steps.map((step,i)=><div className="recipe-entry" key={i}><b>{i+1}</b><textarea required rows="2" placeholder={tr('Mô tả bước nấu')} value={step.text} onChange={e=>changeList('steps',i,{text:e.target.value})}/><label className="tiny-upload"><Camera size={18}/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'steps',i)}/></label><button type="button" onClick={()=>setDraft(d=>({...d,steps:d.steps.filter((_,n)=>i!==n)}))}><Trash2 size={16}/></button>{step.image_key&&<img src={'/api/photos/'+step.image_key} alt=""/>}</div>)}<button type="button" className="text-btn" onClick={()=>setDraft(d=>({...d,steps:[...d.steps,{text:'',image_key:''}]}))}><Plus size={16}/>{tr('Thêm bước')}</button>{feedback&&<p role="alert" className="form-error">{feedback}</p>}<button className="primary submit" disabled={saving}>{tr('Lưu công thức')}</button></form></div></div>}
 </div>
}
