import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Wallet,CalendarDays,HeartPulse,Refrigerator,Shirt,Package,Plus,Search,Sparkles,Mic,Camera,Trash2,Check,ArrowUpRight,X,ChevronRight,RefreshCw,LogOut,ExternalLink,Settings2} from 'lucide-react';
import {Heart,Users,Tags} from 'lucide-react';
import {JarEditor,TaskBoard,Members,Wishlist,Deals,Feedback,FeedbackInbox} from './Extras.jsx';
import {t,languages} from './i18n.js';
import Countdown from './Countdown.jsx';
import FamilyCalendar from './FamilyCalendar.jsx';
import Diary from './Diary.jsx';
import EntryFields from './EntryFields.jsx';
import FinanceView from './FinanceView.jsx';
import Kitchen from './Kitchen.jsx';
import Wardrobe from './Wardrobe.jsx';
import CuraKeeper from './CuraKeeper.jsx';
import {detailsOf,expandRecords,nextOccurrences} from './recurrence.js';
import {iconFor} from './IconPicker.jsx';
import './style.css';
const sections=[['overview','Tổng quan',Home],['finance','Tài chính',Wallet],['calendar','Lịch cả nhà',CalendarDays],['diary','Nhật ký gia đình',Heart],['health','Sức khỏe',HeartPulse],['food','Bếp & thực phẩm',Refrigerator],['wardrobe','Tủ đồ',Shirt],['household','Đồ trong nhà',Package],['wishlist','Wishlist',Heart],['members','Gia đình',Users],['deals','Ưu đãi',Tags],['settings','Cài đặt',Settings2]];
const labels={income:'Thu nhập',expense:'Chi tiêu',claim:'Cần claim',tax:'Thuế',saving:'Tiết kiệm',event:'Lịch hẹn',diary:'Nhật ký gia đình',health:'Sức khỏe',food:'Thực phẩm',meal:'Món nhà hay ăn',wardrobe:'Quần áo / mỹ phẩm',idea:'Ý tưởng phối đồ',household:'Đồ gia dụng',shopping:'Cần mua',task:'Việc cần làm',wishlist:'Wishlist'};
const groups={overview:Object.keys(labels),finance:['expense','income','claim','tax','saving'],calendar:['event'],diary:['diary'],health:['health'],food:['food','meal','shopping'],wardrobe:['wardrobe','idea'],household:['household'],wishlist:['wishlist'],members:[],deals:[],settings:[]};
const sectionFor={income:'finance',expense:'finance',claim:'finance',tax:'finance',saving:'finance',event:'calendar',diary:'diary',health:'health',food:'food',meal:'food',shopping:'food',wardrobe:'wardrobe',idea:'wardrobe',household:'household',task:'overview',wishlist:'wishlist'};
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat('da-DK',{style:'currency',currency:'DKK',maximumFractionDigits:0}).format(n||0);
const empty=kind=>({kind,title:'',person:'Cả nhà',category:'',amount:'',quantity:'',unit:'',date:kind==='food'||kind==='wardrobe'?'':today(),time:'09:00',note:'',image_key:'',frequency:'',repeat_until:'',icon:'',jar_id:'',tags:''});
async function api(path,options){const r=await fetch('/api'+path,{credentials:'same-origin',...options});const data=await r.json();if(!r.ok)throw Error(data.error||'Có lỗi xảy ra');return data}
function meals(items){const have=items.filter(x=>x.kind==='food'&&x.status!=='done'&&(!x.date||x.date>=today())&&(x.quantity==null||x.quantity>0)).map(x=>x.title.toLowerCase());return items.filter(x=>x.kind==='meal').map(x=>{const need=x.note.replace(/^nguyên liệu\s*:/i,'').split(',').map(t=>t.trim()).filter(Boolean);const missing=need.filter(t=>!have.some(y=>y.includes(t.toLowerCase())||t.toLowerCase().includes(y)));return x.title+(missing.length?' · cần mua: '+missing.join(', '):' · nguyên liệu đã có')}).slice(0,5)}
function App(){const [email,setEmail]=useState(null),[authLoading,setAuthLoading]=useState(true),[items,setItems]=useState([]),[events,setEvents]=useState([]),[tab,setTab]=useState('overview'),[person,setPerson]=useState('Tất cả'),[query,setQuery]=useState(''),[form,setForm]=useState(empty('expense')),[dialog,setDialog]=useState(false),[askOpen,setAskOpen]=useState(false),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[members,setMembers]=useState([]),[jars,setJars]=useState([]),[lang,setLang]=useState(()=>localStorage.getItem('family-lang')||'vi');
 const tr=text=>t(text,lang);const people=[...new Set(['Cả nhà',...members.map(x=>x.name),'Bố','Mẹ','Shin'])];
 useEffect(()=>{api('/auth/me').then(async x=>{setEmail(x.email);const [records,calendar,profiles,jarList]=await Promise.allSettled([api('/records'),api('/calendar/events'),api('/members'),api('/jars')]);if(records.status==='fulfilled')setItems(records.value);else setError(records.reason.message);if(calendar.status==='fulfilled')setEvents(calendar.value);if(profiles.status==='fulfilled')setMembers(profiles.value);if(jarList.status==='fulfilled')setJars(jarList.value)}).catch(e=>{if(!e.message.includes('đăng nhập'))setError(e.message)}).finally(()=>setAuthLoading(false))},[]);
 const month=today().slice(0,7),expenses=items.filter(x=>x.kind==='expense'),incomes=items.filter(x=>x.kind==='income'),claims=items.filter(x=>x.kind==='claim'&&x.status!=='done'),shopping=items.filter(x=>x.kind==='shopping'&&x.status!=='done'),future=nextOccurrences(items,today(),new Date(Date.now()+365*86400000).toISOString().slice(0,10),['event']);
 const lastDay=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toISOString().slice(0,10);const monthlyIncome=expandRecords(incomes,month+'-01',lastDay,['income']),monthlyExpenses=expandRecords(expenses,month+'-01',lastDay,['expense']);const income=monthlyIncome.reduce((sum,x)=>sum+Number(x.amount||0),0),spent=monthlyExpenses.reduce((sum,x)=>sum+Number(x.amount||0),0);
 const visible=useMemo(()=>items.filter(x=>groups[tab].includes(x.kind)&&(person==='Tất cả'||x.person===person)&&(x.title+' '+x.category+' '+(x.note||'')).toLowerCase().includes(query.toLowerCase())),[items,tab,person,query]);
 const amounts=expenses.map(x=>x.amount||0).filter(Boolean).sort((a,b)=>a-b),median=amounts.length?amounts[Math.floor(amounts.length/2)]:0,threshold=Math.max(500,median*2.5);
 function navigate(t){setTab(t);setQuery('');setPerson('Tất cả')}
 function add(kind,defaults={}){setForm({...empty(kind),...defaults});setDialog(true);setError('')}
 async function createCountdownEvent(data){const result=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});setItems(xs=>[result,...xs]);return result}
 async function save(e){e.preventDefault();setBusy(true);try{const result=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,details:JSON.stringify({icon:form.icon||undefined,jar_id:form.jar_id||undefined,tags:form.tags?form.tags.split(',').map(x=>x.trim()).filter(Boolean):undefined,recurrence:form.frequency?{frequency:form.frequency,until:form.repeat_until||undefined}:undefined})})});setItems(xs=>[result,...xs]);setDialog(false);navigate(sectionFor[form.kind])}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function update(x,patch){try{await api('/records',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:x.id,...patch})});setItems(xs=>xs.map(y=>y.id===x.id?{...y,...patch}:y))}catch(e){setError(e.message)}}
 async function remove(x){if(!confirm('Xóa mục này khỏi sổ nhà?'))return;try{await api('/records?id='+encodeURIComponent(x.source_id||x.id),{method:'DELETE'});setItems(xs=>xs.filter(y=>y.id!==(x.source_id||x.id)))}catch(e){setError(e.message)}}
 async function upload(file){setBusy(true);try{const data=new FormData();data.append('file',file);const result=await api('/photos',{method:'POST',body:data});setForm(x=>({...x,image_key:result.key}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function sendEvent(x){setBusy(true);try{await api('/calendar/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:x.source_id||x.id})});const calendar=await api('/calendar/events');setEvents(calendar);const records=await api('/records');setItems(records)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function ask(){const q=question.toLowerCase();let a=tr('Tôi có thể tìm dữ liệu đã nhập. Thử hỏi về đồ trong nhà, danh sách mua, chi tiêu hoặc món ăn.');
  if(/ăn gì|nấu gì|món gì|what.*eat|meal|manger|eten|spise/.test(q))a=meals(items).join('\n')||tr('Thêm món nhà hay ăn và nguyên liệu trong bếp để được gợi ý.');
  else if(/mua gì|mua sắm|shopping|to buy|courses|boodschappen|indkøb/.test(q))a=shopping.map(x=>'• '+x.title).join('\n')||tr('Danh sách cần mua đang trống.');
  else if(/chi tiêu|tiền tháng|spend|expenses|dépenses|uitgaven|udgifter/.test(q))a=tr('Đã chi')+' '+money(spent)+' '+tr('và thu')+' '+money(income)+' '+tr('trong tháng này.');
  else if(/có|còn|tìm|stock|have|find|chercher|hebben|har vi/.test(q)){const term=q.replace(/.*(?:có|tìm|còn|have|find|chercher|hebben|har vi)\s*/,'').replace(/\?|ở nhà|không|ko|at home/g,'').trim();const matches=items.filter(x=>['food','wardrobe','household'].includes(x.kind)&&x.title.toLowerCase().includes(term));a=matches.map(x=>x.title+': '+(x.quantity??tr('chưa ghi số lượng'))+' '+(x.unit||'')).join('\n')||tr('Chưa tìm thấy. Thử tên món ngắn hơn.')}setAnswer(a)}
 function listen(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setAnswer('Trình duyệt này chưa hỗ trợ nhập giọng nói.');return}const mic=new Recognition();mic.lang=({vi:'vi-VN',en:'en-US',fr:'fr-FR',nl:'nl-NL',da:'da-DK'})[lang];mic.onresult=e=>setQuestion(e.results[0][0].transcript);mic.start()}
 const row=x=><article className="record" key={x.id}><div className="record-icon">{x.image_key?<img src={'/api/photos/'+x.image_key} alt={x.title}/>:React.createElement(iconFor(x),{size:18})}</div><div className="record-body"><div className="record-title">{x.title}{x.status==='done'&&<span className="done-pill">{tr('Xong')}</span>}{x.kind==='expense'&&x.amount>threshold&&<span className="unusual-pill">{tr('Chi lớn')}</span>}</div><div className="record-meta">{tr(labels[x.kind])} · {x.person}{x.category&&' · '+x.category}{x.date&&' · '+x.date}{detailsOf(x).recurrence&&' · ↻'}{x.kind==='event'&&x.time&&' '+x.time}</div>{x.note&&<p className="record-note">{x.note}</p>}</div><div className="record-end">{x.amount!=null&&<strong>{money(x.amount)}</strong>}{x.quantity!=null&&<span>{x.quantity} {x.unit}</span>}</div><div className="record-actions">{['food','household'].includes(x.kind)&&x.quantity!=null&&<><button title="Giảm một" onClick={()=>update(x,{quantity:Math.max(0,x.quantity-1)})}>−</button><button title="Tăng một" onClick={()=>update(x,{quantity:x.quantity+1})}>+</button></>}{x.kind==='event'&&!detailsOf(x).googleEventId&&<button title="Gửi sang Google Calendar" onClick={()=>sendEvent(x)}><CalendarDays size={17}/></button>}{x.kind==='event'&&detailsOf(x).googleEventId&&<span title="Đã gửi Google Calendar" className="synced"><Check size={15}/></span>}{['claim','shopping','tax'].includes(x.kind)&&x.status!=='done'&&<button title="Đánh dấu xong" onClick={()=>update(x,{status:'done'})}><Check size={17}/></button>}<button title="Xóa" onClick={()=>remove(x)}><Trash2 size={16}/></button></div></article>;
 if(authLoading)return <div className="login"><div className="brand-mark"><Home/></div><p>{tr('Đang mở sổ nhà mình…')}</p></div>;
 if(!email)return <div className="login"><div className="brand-mark"><Home/></div><h1>Cura</h1><p>{tr('Không gian riêng cho bố, mẹ và Shin.')}</p><a className="primary" href="/api/auth/start">{tr('Đăng nhập bằng Google')}</a><label className="language-choice">{tr('Ngôn ngữ')} <select value={lang} onChange={e=>{setLang(e.target.value);localStorage.setItem('family-lang',e.target.value)}}>{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><Feedback api={api} lang={lang}/>{error&&<p className="form-error">{error}</p>}</div>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Home size={22}/></div><div><strong>Cura</strong><small>NHÀ MÌNH</small></div></div><div className="sidebar-label">{tr('KHÔNG GIAN')}</div><nav aria-label="Các mục">{sections.map(([key,label,Icon])=><button key={key} className={'nav '+(tab===key?'active':'')} onClick={()=>navigate(key)}><Icon size={19}/><span>{tr(label)}</span>{key==='food'&&shopping.length>0&&<em>{shopping.length}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="family-avatars"><span>B</span><span>M</span><span>S</span></div><div><strong>{tr('Bố · Mẹ · Shin')}</strong><small>{email}</small></div></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumbs">{tr('Gia đình')} <ChevronRight size={14}/> <strong>{tr(sections.find(x=>x[0]===tab)?.[1])}</strong></div><div className="top-actions"><span className="today">{new Intl.DateTimeFormat(({vi:'vi-VN',en:'en-GB',fr:'fr-FR',nl:'nl-NL',da:'da-DK'})[lang],{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><label className="language-choice compact"><span>{tr('Ngôn ngữ')}</span><select value={lang} onChange={e=>{setLang(e.target.value);localStorage.setItem('family-lang',e.target.value)}}>{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><button className="icon-btn" title="Trợ lý" onClick={()=>setAskOpen(true)}><Sparkles size={19}/></button><button className="icon-btn" title="Đăng xuất" onClick={async()=>{await api('/auth/logout',{method:'POST'});location.reload()}}><LogOut size={18}/></button></div></header>
 <div className="content" key={tab}><div className="heading"><div><div className="eyebrow">{tr('GIA ĐÌNH BỐ · MẸ · SHIN')}</div><h1>{tr(tab==='overview'?'Chào nhà mình 👋':sections.find(x=>x[0]===tab)?.[1])}</h1><p>{tr(tab==='overview'?'Mọi thứ cần nhớ của gia đình, trong một góc nhỏ.':tab==='calendar'?'Lịch của mỗi người và các sự kiện Google Calendar.':tab==='diary'?'Những khoảnh khắc đáng nhớ của cả nhà.':tab==='finance'?'Thu nhập, 6 hũ, chi tiêu, thuế và những khoản cần claim.':tab==='health'?'Giấc ngủ, stress, xét nghiệm và sự lớn lên của Shin.':tab==='food'?'Biết còn gì trong bếp và cần mua gì.':tab==='wardrobe'?'Lưu tủ đồ và những ý tưởng phối đồ.':tab==='household'?'Tìm món đồ trong nhà trước khi mua thêm.':tab==='wishlist'?'Món muốn mua, nơi muốn đến, điều muốn làm.':tab==='members'?'Hồ sơ dùng để gắn việc, lịch và sở thích.':'So sánh giá đã lưu với các món cần mua; kiểm tra giá trên trang cửa hàng trước khi đi.')}</p></div><CuraKeeper tab={tab} lang={lang}/>{!['members','wishlist','deals','diary','settings'].includes(tab)&&<button className="primary" onClick={()=>add(tab==='overview'?'expense':groups[tab][0])}><Plus size={17}/>{tr('Thêm mới')}</button>}</div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}
 {tab==='overview'&&<><div className="overview-grid"><div className="welcome-card"><div className="eyebrow light">{tr('Tháng')} {new Date().getMonth()+1}</div><h2>{tr('Nhịp sống của')}<br/>{tr('nhà mình.')}</h2><p>{tr('Ghi một lần, tìm lại bất cứ lúc nào.')}</p><div className="welcome-actions"><button onClick={()=>add('expense')}><Plus size={16}/>{tr('Ghi khoản chi')}</button><button onClick={()=>add('event')}>{tr('Thêm lịch hẹn')} <ArrowUpRight size={16}/></button></div><div className="decor-ring"/></div><div className="mini-stack"><div className="mini-card"><div><span>{tr('Đã chi tháng này')}</span><strong>{money(spent)}</strong><small>{monthlyExpenses.length} {tr('khoản đã ghi')}</small></div><Wallet size={22}/></div><div className="mini-card"><div><span>{tr('Việc cần để ý')}</span><strong>{claims.length+shopping.length+future.length}</strong><small>{claims.length} {tr('claim')} · {shopping.length} {tr('cần mua')} · {future.length} {tr('lịch')}</small></div><CalendarDays size={22}/></div></div></div><Countdown items={items} googleEvents={events} createEvent={createCountdownEvent} lang={lang}/><TaskBoard items={items} members={members} add={add} update={update} remove={remove} lang={lang}/><div className="overview-columns"><div className="panel"><div className="panel-head"><h2>{tr('Sắp tới')}</h2><button className="text-btn" onClick={()=>navigate('calendar')}>{tr('Xem lịch')} <ChevronRight size={15}/></button></div>{future.length?future.slice(0,3).map(row):<Empty lang={lang} text={tr('Chưa có lịch hẹn.')} action={()=>add('event')}/>}</div><div className="panel"><div className="panel-head"><h2>{tr('Cần xử lý')}</h2></div>{claims.length?claims.slice(0,3).map(row):<Empty lang={lang} text={tr('Không có khoản claim đang chờ.')} action={()=>add('claim')}/>}</div></div></>}
 {tab==='finance'&&<FinanceView items={items} people={people} jars={jars} lang={lang} month={month} onSettings={()=>navigate('settings')}/>}
 {tab==='health'&&<div className="family-strip">{people.filter(x=>x!=='Cả nhà').map((name,i)=><button key={name} className={'person-card '+(person===name?'selected':'')} onClick={()=>setPerson(person===name?'Tất cả':name)}><span className={'person-dot p'+i}>{name[0]}</span><strong>{name}</strong><small>{items.filter(x=>x.kind==='health'&&x.person===name).length} {tr('mục')}</small></button>)}</div>}
 {tab==='calendar'&&<FamilyCalendar items={items} people={people} api={api} lang={lang} onError={setError} add={add}/>}
 {tab==='diary'&&<Diary items={items} setItems={setItems} people={people} api={api} lang={lang} onError={setError}/>}
 {tab==='health'&&<div className="notice"><HeartPulse size={20}/><div><strong>{tr('Nhật ký sức khỏe')}</strong><p>{tr('Ghi giấc ngủ, stress, huyết áp, xét nghiệm máu, tuổi sinh học hoặc chiều cao và cân nặng của Shin. Chưa tự đồng bộ Garmin.')}</p></div></div>}
 {tab==='food'&&<Kitchen items={items} setItems={setItems} api={api} lang={lang} add={add} update={update} remove={remove} onError={setError}/>}
 {tab==='wardrobe'&&<Wardrobe items={items} setItems={setItems} api={api} lang={lang} add={add} remove={remove} members={members} onError={setError}/>}
 {tab==='settings'&&<JarEditor api={api} lang={lang} onSaved={setJars}/>}
 {tab==='wishlist'&&<Wishlist items={items} setItems={setItems} api={api} lang={lang}/>}
 {tab==='members'&&<><Members members={members} setMembers={setMembers} api={api} lang={lang}/><FeedbackInbox api={api} lang={lang}/></>}
 {tab==='deals'&&<Deals items={items} api={api} lang={lang}/>}
 {tab==='household'&&<div className="notice"><Package size={20}/><div><strong>{tr('Nhà có gì?')}</strong><p>{tr('Ghi cả những vật nhỏ, số lượng và vị trí cất trong phần ghi chú; dùng ô tìm kiếm khi đi mua sắm.')}</p></div></div>}
 {!['members','wishlist','deals','diary','settings'].includes(tab)&&<section className="panel records-panel"><div className="panel-head"><div><h2>{tr(tab==='overview'?'Ghi gần đây':'Các mục đã ghi')}</h2><p>{visible.length} {tr('mục')}</p></div><div className="filters"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr('Tìm tên, nhóm, ghi chú')} aria-label="Tìm mục"/></label>{!['health','calendar'].includes(tab)&&<select value={person} onChange={e=>setPerson(e.target.value)} aria-label="Lọc theo người">{['Tất cả',...people].map(x=><option key={x} value={x}>{tr(x)}</option>)}</select>}</div></div>{visible.length?visible.slice(0,tab==='overview'?5:100).map(row):<Empty lang={lang} text={tr(query?'Không tìm thấy.':'Chưa có mục nào.')} action={()=>add(groups[tab][0])}/>}</section>}
 </div></main><button className="floating-assistant" onClick={()=>setAskOpen(true)}><Sparkles size={19}/>{tr('Hỏi quản gia')}</button>
 {dialog&&<div className="modal-backdrop" onClick={()=>setDialog(false)}><div className="modal form-dialog" role="dialog" aria-modal="true" aria-label="Thêm mục" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{tr('Thêm vào nhà mình')}</h2><button onClick={()=>setDialog(false)} aria-label="Đóng"><X/></button></div><form className="entry-form" onSubmit={save}><EntryFields form={form} setForm={setForm} people={people} labels={labels} tr={tr} upload={upload} busy={busy} jars={jars}/>
 {error&&<p className="form-error">{error}</p>}<button className="primary submit" disabled={busy}>{tr(busy?'Đang lưu…':'Lưu mục này')}</button></form></div></div>}
 {askOpen&&<div className="modal-backdrop" onClick={()=>setAskOpen(false)}><div className="modal assistant-dialog" role="dialog" aria-modal="true" aria-label="Hỏi quản gia" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2><Sparkles size={20}/>{tr('Hỏi quản gia')}</h2><button onClick={()=>setAskOpen(false)} aria-label="Đóng"><X/></button></div><p className="assistant-copy">{tr('Tra cứu đồ trong nhà, chi tiêu, danh sách mua và gợi ý món từ dữ liệu đã nhập.')}</p><div className="quick-prompts">{['Tháng này chi tiêu bao nhiêu?','Cần mua gì?','Hôm nay ăn gì?'].map(q=><button key={q} onClick={()=>setQuestion(tr(q))}>{tr(q)}</button>)}</div><div className="assistant-input"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Nhà mình có nước mắm không?"/><button onClick={listen} title="Nhập giọng nói"><Mic size={18}/></button><button className="ask-button" onClick={ask}>{tr('Hỏi')}</button></div>{answer&&<div className="assistant-reply">{answer}</div>}<p className="small-note">{tr('Trợ lý chỉ tra cứu dữ liệu trong nhà. Đọc hóa đơn và chat GPT cần kết nối API riêng; ChatGPT Plus không bao gồm khóa API.')}</p></div></div>}
 </div>}
function Field({title,children}){return <label className="field"><span>{title}</span>{children}</label>}
function Empty({text,action,lang}){return <div className="empty"><span>✳</span><p>{text}</p><button onClick={action}>{t('Thêm mục đầu tiên',lang)} <Plus size={15}/></button></div>}
createRoot(document.getElementById('root')).render(<App/>);
