import React,{useState} from 'react';
import {X,UtensilsCrossed} from 'lucide-react';
import {nutritionForRecipe,nutritionKeys,nutritionUnits} from './nutrition.js';
import {t} from './i18n.js';
const labels={kcal:'Năng lượng',protein:'Đạm',fat:'Chất béo',carbs:'Tinh bột',fiber:'Chất xơ',sodium:'Natri'};
const today=()=>new Date().toISOString().slice(0,10);
export default function MealLogger({recipe,items,people,defaultPerson,onSave,onClose,lang}){
 const tr=x=>t(x,lang),recipes=items.filter(x=>x.kind==='meal');
 const [selected,setSelected]=useState(recipe?.id||''),[title,setTitle]=useState(recipe?.title||''),[person,setPerson]=useState(defaultPerson&&defaultPerson!=='Tất cả'&&defaultPerson!=='Cả nhà'?defaultPerson:people.find(x=>x!=='Cả nhà')||'Mẹ'),[date,setDate]=useState(today),[mealType,setMealType]=useState('Bữa trưa'),[servings,setServings]=useState('1'),[values,setValues]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const picked=recipes.find(x=>x.id===selected),calculated=picked?nutritionForRecipe(picked,items):{nutrition:null,missing:[]};
 function changeRecipe(id){const found=recipes.find(x=>x.id===id);setSelected(id);if(found)setTitle(found.title);setValues({})}
 function submit(e){e.preventDefault();setError('');const amount=Number(servings);if(!Number.isFinite(amount)||amount<=0||amount>100){setError(tr('Số suất ăn không hợp lệ.'));return}const perServing={};for(const key of nutritionKeys){const raw=values[key]!==undefined?values[key]:calculated.nutrition?.[key];if(raw===''||raw==null)continue;const num=Number(raw);if(!Number.isFinite(num)||num<0||num>100000){setError(tr('Chỉ số dinh dưỡng không hợp lệ.'));return}perServing[key]=num}
  const total=Object.fromEntries(Object.entries(perServing).map(([key,num])=>[key,Math.round(num*amount*10)/10]));setBusy(true);
  Promise.resolve(onSave({kind:'meal_log',title:title.trim(),person,date,category:mealType,details:JSON.stringify({recipeId:selected||undefined,servings:amount,nutrition:total,source:Object.keys(values).length?'manual':calculated.nutrition?'recipe':'unknown'})})).then(onClose).catch(e=>setError(e.message)).finally(()=>setBusy(false));
 }
 return <div className="modal-backdrop" onClick={()=>!busy&&onClose()}><div className="modal form-dialog meal-log-dialog" role="dialog" aria-modal="true" aria-label={tr('Ghi bữa ăn')} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2><UtensilsCrossed size={22}/>{tr('Ghi bữa ăn')}</h2><button type="button" onClick={onClose} aria-label={tr('Đóng')}><X/></button></div><form className="entry-form" onSubmit={submit}>
  <label className="field"><span>{tr('Chọn món đã lưu (nếu có)')}</span><select value={selected} onChange={e=>changeRecipe(e.target.value)}><option value="">{tr('Nhập món khác')}</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>
  <label className="field"><span>{tr('Món đã ăn')} *</span><input required maxLength="180" value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="form-row"><label className="field"><span>{tr('Người ăn')}</span><select value={person} onChange={e=>setPerson(e.target.value)}>{people.filter(p=>p!=='Cả nhà').map(p=><option key={p} value={p}>{tr(p)}</option>)}</select></label><label className="field"><span>{tr('Ngày ăn')}</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>
  <div className="form-row"><label className="field"><span>{tr('Bữa')}</span><select value={mealType} onChange={e=>setMealType(e.target.value)}>{['Bữa sáng','Bữa trưa','Bữa tối','Ăn nhẹ'].map(p=><option key={p} value={p}>{tr(p)}</option>)}</select></label><label className="field"><span>{tr('Số suất đã ăn')}</span><input type="number" required min="0.1" max="100" step="0.1" value={servings} onChange={e=>setServings(e.target.value)}/></label></div>
  <div className="food-nutrition-input"><strong>{tr('Dinh dưỡng mỗi suất')}</strong>{picked&&<p>{calculated.nutrition?tr('Đã tính từ công thức; có thể sửa số nếu cần.'):tr('Chưa đủ dữ liệu dinh dưỡng cho công thức; điền theo nhãn hoặc để trống.')}</p>}<div className="nutrition-fields">{nutritionKeys.map(key=><label className="field" key={key}><span>{tr(labels[key])} ({nutritionUnits[key]})</span><input type="number" min="0" step="0.01" value={values[key]??calculated.nutrition?.[key]??''} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}</div></div>
  <p className="small-note">{tr('Ô trống được hiển thị là chưa biết, không tính bằng 0. Số liệu nhập tay chỉ là ước tính.')}</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary submit" disabled={busy||!title.trim()}>{tr(busy?'Đang lưu…':'Lưu bữa ăn')}</button>
 </form></div></div>
}
