import React,{useState} from 'react';
import {Shirt,Plus,Camera,ChevronLeft,ChevronRight,X,Trash2,Tag,Sparkles,RotateCcw} from 'lucide-react';
import {detailsOf} from './recurrence.js';
import {t} from './i18n.js';
const seasons=['đông','thu','hè','xuân','mẹ','bố','Shin'];
function slotOf(x){const name=(x.category+' '+x.title).toLowerCase();return /giày|dép|shoe|boot/.test(name)?'shoes':/quần|váy|chân váy|pants|skirt/.test(name)?'bottom':'top'}
async function removeFlatBackground(file,threshold=38){const bmp=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;const ctx=canvas.getContext('2d');ctx.drawImage(bmp,0,0);const image=ctx.getImageData(0,0,canvas.width,canvas.height),data=image.data;const corners=[0,(canvas.width-1)*4,(canvas.width*(canvas.height-1))*4,(canvas.width*canvas.height-1)*4];const avg=[0,1,2].map(c=>corners.reduce((sum,i)=>sum+data[i+c],0)/4);const dist=i=>Math.hypot(data[i]-avg[0],data[i+1]-avg[1],data[i+2]-avg[2]);for(let i=0;i<data.length;i+=4)if(dist(i)<threshold)data[i+3]=0;ctx.putImageData(image,0,0);return await new Promise(resolve=>canvas.toBlob(resolve,'image/png'))}
export default function Wardrobe({items,setItems,api,lang,add,remove,members,onError}){
 const tr=x=>t(x,lang),clothes=items.filter(x=>x.kind==='wardrobe'),ideas=items.filter(x=>x.kind==='idea');
 const [open,setOpen]=useState(false),[filter,setFilter]=useState('all'),[frame,setFrame]=useState(0),[outfit,setOutfit]=useState({title:'',photos:[],markers:[]}),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[chosen,setChosen]=useState({top:'',bottom:'',shoes:''}),[active,setActive]=useState(null);
 const filtered=clothes.filter(x=>filter==='all'||(detailsOf(x).tags||[]).some(tag=>tag.toLocaleLowerCase()===filter.toLocaleLowerCase()));
 const stories=ideas.flatMap(x=>{const d=detailsOf(x);return d.type==='outfit'?(d.photos||[]).map((key,index)=>({key,x,index,markers:(d.markers||[]).filter(m=>m.photo===index)})):[]});
 const current=stories[Math.max(0,Math.min(frame,stories.length-1))];
 async function upload(files){setBusy(true);setMessage('');try{const next=[];for(const file of files){const fd=new FormData();fd.append('file',file);const r=await api('/photos',{method:'POST',body:fd});next.push(r.key)}setOutfit(d=>({...d,photos:[...d.photos,...next]}))}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function save(e){e.preventDefault();setBusy(true);try{if(!outfit.photos.length)throw Error(tr('Thêm ít nhất một ảnh outfit.'));const details=JSON.stringify({type:'outfit',photos:outfit.photos,markers:outfit.markers});const row=await api('/records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'idea',title:outfit.title||tr('Outfit của nhà mình'),person:'Mẹ',image_key:outfit.photos[0],details})});setItems(xs=>[row,...xs]);setEditing(false);setOutfit({title:'',photos:[],markers:[]});setFrame(stories.length)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 function marker(e,photo){const rect=e.currentTarget.getBoundingClientRect(),x=Math.round((e.clientX-rect.left)/rect.width*100),y=Math.round((e.clientY-rect.top)/rect.height*100);setActive({photo,x,y})}
 function addMarker(id){setOutfit(d=>({...d,markers:[...d.markers,{...active,wardrobeId:id}]}));setActive(null)}
 async function cutout(file){setBusy(true);setMessage('');try{const blob=await removeFlatBackground(file);const fd=new FormData();fd.append('file',blob,'outfit-cutout.png');const r=await api('/photos',{method:'POST',body:fd});setOutfit(d=>({...d,photos:[...d.photos,r.key]}))}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const mother=members.find(x=>/mẹ|mom|nhung/i.test(x.name))||members[0];
 function suggest(){const season=filter==='all'?'':filter;const eligible=clothes.filter(x=>!season||(detailsOf(x).tags||[]).includes(season));setChosen({top:eligible.find(x=>slotOf(x)==='top')?.id||'',bottom:eligible.find(x=>slotOf(x)==='bottom')?.id||'',shoes:eligible.find(x=>slotOf(x)==='shoes')?.id||''});setMessage(tr('Thử đổi từng món để hoàn thiện outfit.'))}
 return <div className="wardrobe-page"><section className="panel closet-panel"><div className="panel-head"><div><h2>{tr('Tủ đồ nhà mình')}</h2><p>{tr('Mở cửa tủ, xem ảnh món đồ và lọc theo mùa hoặc thành viên.')}</p></div><button className="text-btn" onClick={()=>add('wardrobe')}><Plus size={16}/>{tr('Thêm món đồ')}</button></div><div className="closet-controls">{['all',...seasons].map(tag=><button key={tag} className={filter===tag?'selected':''} onClick={()=>setFilter(tag)}>{tag==='all'?tr('Tất cả'):tag}</button>)}</div><div className="closet-scene"><div className={'closet-door left'+(open?' opened':'')} onClick={()=>setOpen(true)} role="button" tabIndex="0" onKeyDown={e=>e.key==='Enter'&&setOpen(true)}><Shirt size={45}/><span>{tr('Chạm để mở tủ')}</span></div><div className={'closet-door right'+(open?' opened':'')} onClick={()=>setOpen(true)}/><div className="closet-interior"><div className="closet-rail"/><div className="closet-items">{filtered.map(x=><article className="closet-item" id={'closet-'+x.id} key={x.id}><div className="closet-hanger">⌄</div>{x.image_key?<img src={'/api/photos/'+x.image_key} alt={x.title}/>:<Shirt size={42}/>}<strong>{x.title}</strong><small>{(detailsOf(x).tags||[]).map(tag=>'#'+tag).join(' ')}</small><button onClick={()=>remove(x)} title={tr('Xóa')}><Trash2 size={15}/></button></article>)}{!filtered.length&&<p className="hint">{tr('Không có món đồ theo bộ lọc này.')}</p>}</div></div></div>{open&&<button className="text-btn" onClick={()=>setOpen(false)}>{tr('Đóng cửa tủ')}</button>}</section>
 <section className="panel outfit-journal"><div className="panel-head"><div><h2>{tr('Nhật ký phối đồ')}</h2><p>{tr('Mỗi khung là một ảnh; chạm vào điểm đánh dấu để mở món đồ trong tủ.')}</p></div><button className="text-btn" onClick={()=>setEditing(true)}><Camera size={17}/>{tr('Thêm outfit')}</button></div>{current?<div className="outfit-carousel"><button onClick={()=>setFrame((frame-1+stories.length)%stories.length)} aria-label={tr('Ảnh trước')}><ChevronLeft/></button><div className="outfit-frame"><img src={'/api/photos/'+current.key} alt={current.x.title}/>{current.markers.map((m,i)=>{const found=clothes.find(x=>x.id===m.wardrobeId);return found&&<button key={i} className="outfit-pin" style={{left:m.x+'%',top:m.y+'%'}} onClick={()=>{setOpen(true);setFilter('all');document.getElementById('closet-'+found.id)?.scrollIntoView({behavior:'smooth',block:'center'})}} title={found.title}><span>+</span><small>{found.title}</small></button>})}</div><button onClick={()=>setFrame((frame+1)%stories.length)} aria-label={tr('Ảnh sau')}><ChevronRight/></button><div className="outfit-caption"><strong>{current.x.title}</strong><small>{frame+1}/{stories.length}</small></div></div>:<p className="hint">{tr('Chưa có ảnh outfit nào.')}</p>}</section>
 <section className="panel mannequin-section"><div className="panel-head"><div><h2>{tr('Thử phối đồ')}</h2><p>{tr('Mannequin minh họa chuyển động; chọn ảnh đại diện Mẹ để đặt khuôn mặt vào mẫu.')}</p></div><button className="text-btn" onClick={suggest}><Sparkles size={17}/>{tr('Gợi ý từ tủ đồ')}</button></div><div className="mannequin-layout"><div className="mannequin-stage"><div className="mannequin-3d"><div className="mannequin-head">{mother?.avatar_key?<img src={'/api/photos/'+mother.avatar_key} alt=""/>:'☺'}</div><div className="mannequin-neck"/><div className="mannequin-arms"/><div className="mannequin-torso">{clothes.find(x=>x.id===chosen.top)?.image_key&&<img src={'/api/photos/'+clothes.find(x=>x.id===chosen.top).image_key} alt=""/>}</div><div className="mannequin-legs">{clothes.find(x=>x.id===chosen.bottom)?.image_key&&<img src={'/api/photos/'+clothes.find(x=>x.id===chosen.bottom).image_key} alt=""/>}</div><div className="mannequin-shoes">{clothes.find(x=>x.id===chosen.shoes)?.image_key&&<img src={'/api/photos/'+clothes.find(x=>x.id===chosen.shoes).image_key} alt=""/>}</div></div></div><div className="mannequin-picks">{[['top','Áo / phụ kiện'],['bottom','Quần / váy'],['shoes','Giày']].map(([slot,label])=><label key={slot} className="field"><span>{tr(label)}</span><select value={chosen[slot]} onChange={e=>setChosen(x=>({...x,[slot]:e.target.value}))}><option value="">{tr('Chọn món đồ')}</option>{clothes.filter(x=>slotOf(x)===slot).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>)}<p className="hint">{tr('Mẫu này là hình minh họa có chuyển động, không phải bản dựng 3D cá nhân từ ảnh cơ thể.')}</p></div></div></section>
 {message&&<p className="hint" role="status">{message}</p>}
 {editing&&<div className="modal-backdrop" onClick={()=>!busy&&setEditing(false)}><div className="modal form-dialog outfit-editor" role="dialog" aria-modal="true" aria-label={tr('Thêm outfit')} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{tr('Thêm outfit')}</h2><button onClick={()=>setEditing(false)} aria-label={tr('Đóng')}><X/></button></div><form className="entry-form" onSubmit={save}><label className="field"><span>{tr('Tên outfit')}</span><input value={outfit.title} onChange={e=>setOutfit(d=>({...d,title:e.target.value}))} placeholder="Đi chơi mùa thu"/></label><label className="upload"><Camera size={17}/>{tr('Chọn ảnh (có thể chọn nhiều)')}<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{upload([...e.target.files]);e.target.value=''}}/></label><label className="upload"><Sparkles size={17}/>{tr('Tách nền đơn sắc của một ảnh')}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&cutout(e.target.files[0])}/></label><p className="hint">{tr('Tách nền đơn sắc hoạt động tốt khi nền đồng màu; nền phức tạp cần dịch vụ AI riêng.')}</p>{outfit.photos.map((key,i)=><div className="outfit-edit-photo" key={key}><button type="button" className="outfit-photo-target" onClick={e=>marker(e,i)} title={tr('Chạm vào món đồ trong ảnh để gắn tag')}><img src={'/api/photos/'+key} alt={tr('Ảnh outfit')+' '+(i+1)}/>{outfit.markers.filter(m=>m.photo===i).map((m,n)=><span key={n} className="outfit-pin" style={{left:m.x+'%',top:m.y+'%'}}>+</span>)}</button><button type="button" className="text-btn" onClick={()=>setOutfit(d=>({...d,photos:d.photos.filter((_,n)=>i!==n),markers:d.markers.filter(m=>m.photo!==i).map(m=>({...m,photo:m.photo>i?m.photo-1:m.photo}))}))}><Trash2 size={15}/>{tr('Xóa ảnh')}</button></div>)}{active&&<div className="marker-picker"><p>{tr('Chọn món đồ ở vị trí vừa chạm')}</p><select onChange={e=>e.target.value&&addMarker(e.target.value)} defaultValue=""><option value="">{tr('Chọn món đồ')}</option>{clothes.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button type="button" onClick={()=>setActive(null)}><X size={16}/></button></div>}{message&&<p className="form-error">{message}</p>}<button className="primary submit" disabled={busy}>{tr('Lưu outfit')}</button></form></div></div>}
 </div>
}
